# Generated by Django 5.0.2 on 2024-04-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id_number',
        ),
    ]
