# Generated by Django 5.0.2 on 2024-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_staff_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
