# Generated by Django 5.0.2 on 2024-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_equipment_equipment_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='disposal_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
