# Generated by Django 5.0.2 on 2024-04-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_equipment_disposal_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_model',
            name='role',
        ),
        migrations.DeleteModel(
            name='Administrators',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='stdnum',
        ),
        migrations.RemoveField(
            model_name='schoolclasses',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stdclass',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='schoolclass',
        ),
        migrations.DeleteModel(
            name='SchoolInfo',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Supportstaff',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='Admin_Model',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Schoolclasses',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
