# Generated by Django 5.0.2 on 2024-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_admin_model_role_delete_administrators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=150, verbose_name='School name')),
                ('badge', models.ImageField(blank=True, null=True, upload_to='school_badge/')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('box_number', models.CharField(max_length=50, verbose_name='Box Number')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectname', models.CharField(max_length=25, verbose_name='Subject Name')),
                ('subjectid', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Subject id')),
                ('subjecthead', models.CharField(max_length=25, verbose_name='Head of Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schoolclasses',
            fields=[
                ('classid', models.AutoField(primary_key=True, serialize=False, verbose_name='Class id')),
                ('classname', models.CharField(max_length=20, verbose_name='Class Name')),
                ('classteacher', models.CharField(blank=True, max_length=20, null=True, verbose_name='Class teacher')),
                ('subjects', models.ManyToManyField(to='frontend.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Teacher id')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('teachernames', models.CharField(max_length=100, verbose_name='Teachers Names')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(default=None, verbose_name='Date of Birth')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('joiningdate', models.DateField(default=None, verbose_name='Joining Date')),
                ('qualification', models.CharField(max_length=100, verbose_name='Academic Qualifications')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('salary', models.CharField(default=None, max_length=100, verbose_name='Salary')),
                ('bankaccnum', models.CharField(default=None, max_length=100, verbose_name='Bank Account No.')),
                ('classes', models.ManyToManyField(to='frontend.schoolclasses')),
                ('subjects', models.ManyToManyField(to='frontend.subjects')),
            ],
        ),
    ]
