# Generated by Django 5.0.2 on 2024-04-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_schoolinfo_subjects_schoolclasses_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclasses',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
