# Generated by Django 5.0.2 on 2024-04-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_schoolclasses_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Schoolclasses',
        ),
    ]
