# Generated by Django 5.0.2 on 2024-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_teachers_classes_delete_schoolclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=25, verbose_name='Username')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Enter the password')),
            ],
        ),
    ]
