# Generated by Django 5.0.2 on 2024-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_otherusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
