# Generated by Django 5.0.2 on 2024-05-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
