# Generated by Django 5.0.2 on 2024-05-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_delete_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolInfo',
        ),
    ]
